name: influencer_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
  intl: any
  

  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_storage: ^11.4.0
  flutter_gen: ^5.3.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_bloc: ^8.1.3
  dots_indicator: ^3.0.0
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  flutter_riverpod: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  flavor: ^2.0.0
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.11.0
  bloc: ^8.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.1.0
  firebase_messaging: ^14.7.2
  firebase_crashlytics: ^3.4.2
  image_picker: ^1.0.4
  fluttertoast: ^8.2.2
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/png/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
