// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu7X__Drn7vQpBeZ-4shj93XJruQrAvWw',
    appId: '1:814480283753:web:d60a2caa8696cb60dcaaf8',
    messagingSenderId: '814480283753',
    projectId: 'influencer-112b4',
    authDomain: 'influencer-112b4.firebaseapp.com',
    storageBucket: 'influencer-112b4.appspot.com',
    measurementId: 'G-Y7RTJ6SR61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWfNRNCniM7jFwBP_cJceR1YsxlzHAMU',
    appId: '1:814480283753:android:70f6a6aebd1b4645dcaaf8',
    messagingSenderId: '814480283753',
    projectId: 'influencer-112b4',
    storageBucket: 'influencer-112b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXfZAPDT_gXf2cLbwBdnn4z8Va2JFR5Y',
    appId: '1:814480283753:ios:849bbfbff9143e24dcaaf8',
    messagingSenderId: '814480283753',
    projectId: 'influencer-112b4',
    storageBucket: 'influencer-112b4.appspot.com',
    iosBundleId: 'com.example.influencerApp',
  );
}
